11 data scope funded research gtr
innovation-growth-lab/alphafold-impact pull request #26
Opened 2024-01-23 08:31 UTC by ampudia19

## Title: Refactor of data collection OA code and new GtR modules

### Description

In this PR, I've included a major refactor of our data collection code for OpenAlex (OA), and introduced new modules for data collection and processing for Gateway to Research (GtR).

### Key Changes

1. **OA Data Collection Code Refactor:**
   - I've restructured the OA data collection code to enhance its modularity and functionality. This includes moving some parts to `utils.py`.

2. **Introduction of GtR Data Collection and Processing:**
   - New modules for fetching and processing GtR data have been added.

### Specific Requests

- **Jack's Review on OA Code:**
   - Jack, could you please check the functionality of the old OA code, especially the parts I've moved around? I've tried to make sure nothing breaks, but you never know. Adding some tests on your code may help in the future.
   - Additionally, there's a bit of redundancy in the code, particularly between the two similar request functions. It would be great if you could look into yours, see whether your code can use mine instead.

- **Harmonisation of Hierarchical Naming:**
   - I've noticed that the hierarchical naming in both parameters and catalog names could be better aligned. Currently, I've kept yours as top-level, but ideally, they should be nested under `<oa>`. See the other parameters for reference.
   - Any suggestions on restructuring these for consistency and clarity is appreciated :)

2024-01-25 16:48 UTC, Jack-0-0 requested changes
@ampudia19 I have reviewed the PR and left some comments.

In a separate PR, I will make changes relating to my parts of the OA code so that they fit with the new conventions.

2024-01-25 16:48 UTC, Jack-0-0 commented on conf/base/catalog.yml
The new format `catalog.yml` looks good. I didn't know about yaml anchors and aliases.

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/pipeline.py
> +        )
Can use a list comprehension here:
```suggestion
     pipelines = [
        pipeline(
            template_pipeline,
            parameters={"params:test": "test"},
            namespace=f"gtr.data_collection.{label}",
            tags=[label.rsplit('/', maxsplit=1)[-1], "gtr"],
        )
        for label in settings.DYNAMIC_PIPELINES_MAPPING["gtr"]
    ]
```

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/utils.py
> +"""
This docstring is missing a function description for `transform_nested_dict`.
Also, the functions in the docstring start with `_` but the functions do not.

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/nodes.py
> +def preprocess_data_to_df(raw_data: List[Dict[str, Any]], endpoint) -> pd.DataFrame:
`endpoint` is missing a typehint.

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/nodes.py
> +        raw_data (List[Dict[str, Any]]): The raw data in a list of dictionaries.
`endpoint` is missing from the docstring

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/nodes.py
> +    parameters: Dict[str, Union[str, int]], endpoint, test: bool = False
`endpoint` is missing a typehint

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_gtr/nodes.py
> +        endpoint (str): The endpoint to fetch data from.
`test` is missing from the docstring

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_oa/README.md
This is nicer than before 🙂

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_oa/nodes.py
> +                oa_doi_dict[work_id]["referenced_works"] = ref_works
```suggestion
oa_doi_dict[work_id] = {"doi": doi, "referenced_works": ref_works}
```

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_collection_oa/pipeline.py
> +    pipelines = []
Can use a list comprehension here

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_processing_gtr/nodes.py
> +"""
This doesn't have the function descriptions like the other modules.

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_processing_gtr/nodes.py
> +def process_institutions(gtr_authors: List[dict]):
Missing a return typehint here

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_processing_gtr/nodes.py
> +def process_publications(gtr_publications: List[dict]):
Missing a return typehint here

2024-01-25 16:48 UTC, Jack-0-0 commented on src/alphafold_impact/pipelines/data_processing_gtr/nodes.py
> +def process_alphafold_citations(reference_dict, cites_data):
Missing typehints here

2024-01-29 09:13 UTC, ampudia19 commented on conf/base/catalog.yml
I didn't either! Quite handy when expected to keep all dataset references in a single file :)

2024-01-29 09:21 UTC, merged